#!/usr/bin/env python3
import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
import yaml

STARTER_MANIFEST = """# hybrid-syncer configuration manifest
hybrid_repo: "./sample-repos/hybrid"
default_branch: "master"

authoring:
  default_email: "syncer@example.com"
  default_name: "Hybrid Syncer"

targets:
  repo-1-a:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "a"
    hybrid:
      path: "repo-1/a"

  repo-1-b:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "b"
    hybrid:
      path: "repo-1/b"

  repo-2-a:
    origin:
      url: "./sample-repos/repo-2.git"
      path: "a"
    hybrid:
      path: "repo-2/a"
"""

RED = "\033[91m\033[1m"
RESET = "\033[0m"


def clean_path(p) -> str:
    if not p or p == ".":
        return ""
    return str(p).strip("/")


def load_manifest(config_path: Path) -> dict:
    if not config_path.exists():
        print(f"Error: Configuration file '{config_path}' not found.", file=sys.stderr)
        print("Run 'hybrid-syncer init' to create a starter sync-manifest.yaml.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception as e:
        print(f"Error reading configuration file '{config_path}': {e}", file=sys.stderr)
        sys.exit(1)

    if "targets" not in data or not isinstance(data.get("targets"), dict):
        print(f"Error: Invalid manifest format in '{config_path}'. 'targets' section missing or invalid.", file=sys.stderr)
        sys.exit(1)

    return data


def is_remote_url(url: str) -> bool:
    if not url:
        return False
    return url.startswith(("http://", "https://", "git@", "ssh://"))


def check_remote_repo_exists(url: str) -> bool:
    """Checks if a remote repository exists and is accessible via git ls-remote."""
    rc, _, _ = run_git(["ls-remote", url])
    return rc == 0


def check_repo_exists(url: str) -> tuple[bool, str]:
    """
    Checks whether a repository exists on disk (if local) or via git ls-remote (if remote URL).
    Returns (exists, error_message_suffix).
    """
    if is_remote_url(url):
        if check_remote_repo_exists(url):
            return True, ""
        return False, "is not accessible or does not exist."
    else:
        if Path(url).exists():
            return True, ""
        return False, "does not exist on disk."


def resolve_repo_url(url: str, base_dir: Path) -> str:
    if not url:
        return ""
    if url.startswith(("http://", "https://", "git@", "ssh://")):
        return url
    if url.startswith("file://"):
        url = url[7:]
    p = Path(url)
    if not p.is_absolute():
        p = (base_dir / p).resolve()
    return str(p)


def format_exclude_pattern(pattern: str, base_path: str) -> list[str]:
    pattern = pattern.strip()
    if not base_path:
        return [pattern]
    if pattern.startswith(base_path + "/"):
        return [pattern]
    if pattern.startswith("**/"):
        suffix = pattern[3:]
        return [f"{base_path}/{suffix}", f"{base_path}/**/{suffix}"]
    return [f"{base_path}/{pattern}"]


def build_glob_expr(base_path: str, exclude_patterns: list[str] | None = None) -> str:
    include_pattern = f"{base_path}/**" if base_path else "**"

    if not exclude_patterns:
        return f'glob(["{include_pattern}"])'

    formatted_excludes = []
    for p in exclude_patterns:
        if isinstance(p, str) and p.strip():
            formatted_excludes.extend(format_exclude_pattern(p, base_path))

    if not formatted_excludes:
        return f'glob(["{include_pattern}"])'

    excludes_str = ", ".join(f'"{p}"' for p in formatted_excludes)
    return f'glob(["{include_pattern}"], exclude = [{excludes_str}])'


def generate_sky_config(manifest: dict, target_filter: str = "", config_path: str = "sync-manifest.yaml") -> str:
    targets = manifest.get("targets", {})
    base_dir = Path(config_path).parent.resolve()

    if target_filter:
        if target_filter not in targets:
            available = ", ".join(targets.keys()) or "none"
            print(f"Error: Target '{target_filter}' not found in manifest. Available targets: {available}", file=sys.stderr)
            sys.exit(1)
        targets_to_gen = {target_filter: targets[target_filter]}
    else:
        targets_to_gen = targets

    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")
    default_branch = manifest.get("default_branch", "main")
    authoring_cfg = manifest.get("authoring", {})
    author_email = authoring_cfg.get("default_email", "syncer@example.com")
    author_name = authoring_cfg.get("default_name", "Hybrid Syncer")
    author_str = f"{author_name} <{author_email}>"

    lines = [
        f"# Generated by hybrid-syncer from {config_path}",
        "# Do not edit manually.",
        ""
    ]

    for t_name, t_cfg in targets_to_gen.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        raw_origin_url = origin_cfg.get("url")
        if not raw_origin_url:
            print(f"Error: Target '{t_name}' is missing origin.url", file=sys.stderr)
            sys.exit(1)

        origin_url = resolve_repo_url(raw_origin_url, base_dir)
        origin_branch = origin_cfg.get("branch", default_branch)
        origin_path = clean_path(origin_cfg.get("path", ""))

        raw_hybrid_url = hybrid_cfg.get("url", default_hybrid_url)
        hybrid_url = resolve_repo_url(raw_hybrid_url, base_dir)
        hybrid_branch = hybrid_cfg.get("branch", default_branch)
        hybrid_path = clean_path(hybrid_cfg.get("path", ""))

        mode = t_cfg.get("mode", "ITERATIVE")

        # Collect exclusion patterns
        target_exclude = t_cfg.get("exclude", [])
        if isinstance(target_exclude, str):
            target_exclude = [target_exclude]
        elif not isinstance(target_exclude, list):
            target_exclude = []

        origin_exclude_raw = origin_cfg.get("exclude", [])
        if isinstance(origin_exclude_raw, str):
            origin_exclude_raw = [origin_exclude_raw]
        elif not isinstance(origin_exclude_raw, list):
            origin_exclude_raw = []

        hybrid_exclude_raw = hybrid_cfg.get("exclude", [])
        if isinstance(hybrid_exclude_raw, str):
            hybrid_exclude_raw = [hybrid_exclude_raw]
        elif not isinstance(hybrid_exclude_raw, list):
            hybrid_exclude_raw = []

        origin_exclude = origin_exclude_raw + target_exclude
        hybrid_exclude = hybrid_exclude_raw + target_exclude

        # Origin files & destination files patterns
        origin_files_push = build_glob_expr(origin_path, origin_exclude)
        dest_files_push = build_glob_expr(hybrid_path, hybrid_exclude)

        # Transformations for push
        push_trans = ""
        if origin_path != hybrid_path:
            push_trans = f'\n    transformations = [\n        core.move("{origin_path}", "{hybrid_path}"),\n    ],'

        # Workflow: push
        lines.append(f"# Target: {t_name} (push)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-push",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        ref = "{origin_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        fetch = "{hybrid_branch}",')
        lines.append(f'        push = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {origin_files_push},")
        lines.append(f"    destination_files = {dest_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{push_trans}')
        lines.append(")")
        lines.append("")

        # Transformations for pull
        pull_trans = ""
        if hybrid_path != origin_path:
            pull_trans = f'\n    transformations = [\n        core.move("{hybrid_path}", "{origin_path}"),\n    ],'

        # Workflow: pull
        lines.append(f"# Target: {t_name} (pull)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-pull",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        ref = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        fetch = "{origin_branch}",')
        lines.append(f'        push = "{origin_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {dest_files_push},")
        lines.append(f"    destination_files = {origin_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{pull_trans}')
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def handle_init(args):
    config_path = args.config
    if config_path.exists() and not args.force:
        print(f"Error: File '{config_path}' already exists. Use -f / --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    try:
        if config_path.parent:
            config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(STARTER_MANIFEST, encoding="utf-8")
        print(f"Initialized starter sync manifest at: {config_path}")
    except Exception as e:
        print(f"Error writing manifest to '{config_path}': {e}", file=sys.stderr)
        sys.exit(1)


def handle_generate(args):
    manifest = load_manifest(args.config)
    sky_content = generate_sky_config(manifest, target_filter=args.target, config_path=str(args.config))

    if args.output:
        try:
            if args.output.parent:
                args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(sky_content, encoding="utf-8")
            print(f"Generated Starlark configuration written to: {args.output}")
        except Exception as e:
            print(f"Error writing output to '{args.output}': {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(sky_content)


def run_git(args: list, cwd=None) -> tuple[int, str, str]:
    """Helper to execute git commands and return (returncode, stdout, stderr)."""
    try:
        res = subprocess.run(
            ["git"] + args,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        return res.returncode, res.stdout, res.stderr
    except Exception as e:
        return -1, "", str(e)


def check_clean_workspace(repo_url: str) -> list[str]:
    """
    Checks if a local non-bare git workspace has uncommitted changes.
    Returns list of porcelain status lines if uncommitted changes exist.
    """
    if not repo_url:
        return []
    repo_path = Path(repo_url)
    if not repo_path.is_dir():
        return []

    # Check if bare
    rc, out, _ = run_git(["-C", str(repo_path), "rev-parse", "--is-bare-repository"])
    if rc == 0 and out.strip() == "true":
        if str(repo_path).endswith(".git"):
            sibling_working_dir = Path(str(repo_path)[:-4])
            if sibling_working_dir.is_dir():
                return check_clean_workspace(str(sibling_working_dir))
        return []

    rc, out, _ = run_git(["-C", str(repo_path), "status", "--porcelain"])
    if rc == 0 and out.strip():
        return [line for line in out.strip().splitlines() if line.strip()]

    return []


def _parse_log_for_revid(log_out: str) -> tuple[str | None, str | None]:
    blocks = log_out.split("\x00")
    revid_pattern = re.compile(r"GitOrigin-RevId:\s*([0-9a-fA-F]{7,40})")

    for block in blocks:
        block = block.strip()
        if not block:
            continue
        lines = block.splitlines()
        commit_sha = lines[0].strip()
        body = "\n".join(lines[1:])
        match = revid_pattern.search(body)
        if match:
            return commit_sha, match.group(1)
    return None, None


def find_last_sync_info(dest_repo_url: str, dest_path: str = "") -> tuple[str | None, str | None]:
    """
    Searches dest_repo commit log for the last Copybara sync commit containing GitOrigin-RevId.
    Returns (dest_commit_sha, source_origin_sha) or (None, None).
    """
    dest_path_obj = Path(dest_repo_url)
    if not dest_path_obj.exists():
        return None, None

    cmd = ["-C", str(dest_path_obj), "log", "--grep=GitOrigin-RevId:", "-n", "50", "--format=%H%n%B%x00"]
    if dest_path:
        cmd_with_path = cmd + ["--", dest_path]
        rc, out, _ = run_git(cmd_with_path)
        if rc == 0 and out.strip():
            sha, rev = _parse_log_for_revid(out)
            if sha and rev:
                return sha, rev

    rc, out, _ = run_git(cmd)
    if rc == 0 and out.strip():
        return _parse_log_for_revid(out)

    return None, None


def find_effective_sync_point(source_url: str, source_path: str, dest_url: str, dest_path: str) -> tuple[str | None, str | None]:
    """
    Finds the most recent sync point (source_last_sync_sha, dest_last_sync_sha) between source and dest repositories.
    Checks GitOrigin-RevId in both dest log (push) and source log (pull) to find the newest sync point.
    Returns (source_sync_sha, dest_sync_sha) or (None, None).
    """
    dest_commit_sha1, source_rev_id1 = find_last_sync_info(dest_url, dest_path)
    source_commit_sha2, dest_rev_id2 = find_last_sync_info(source_url, source_path)

    if not (dest_commit_sha1 and source_rev_id1) and not (source_commit_sha2 and dest_rev_id2):
        return None, None

    if (dest_commit_sha1 and source_rev_id1) and not (source_commit_sha2 and dest_rev_id2):
        return source_rev_id1, dest_commit_sha1

    if not (dest_commit_sha1 and source_rev_id1) and (source_commit_sha2 and dest_rev_id2):
        return source_commit_sha2, dest_rev_id2

    # Compare which sync point is newer in source repository history
    source_path_obj = Path(source_url)
    if source_path_obj.exists():
        rc, _, _ = run_git(["-C", str(source_path_obj), "merge-base", "--is-ancestor", source_rev_id1, source_commit_sha2])
        if rc == 0:
            return source_commit_sha2, dest_rev_id2

    return source_rev_id1, dest_commit_sha1


def check_ancestry_history(source_repo_url: str, last_sync_source_sha: str) -> bool:
    """
    Checks if last_sync_source_sha is still an ancestor of HEAD in source_repo.
    Returns False if history was rewritten / rebased / force-pushed.
    """
    source_path_obj = Path(source_repo_url)
    if not source_path_obj.exists():
        return True

    # Check commit existence
    rc, _, _ = run_git(["-C", str(source_path_obj), "cat-file", "-e", f"{last_sync_source_sha}^{{commit}}"])
    if rc != 0:
        return False

    rc, _, _ = run_git(["-C", str(source_path_obj), "merge-base", "--is-ancestor", last_sync_source_sha, "HEAD"])
    return rc == 0


def get_new_commits_count(repo_url: str, from_sha: str, path_filter: str = "") -> int:
    repo_path_obj = Path(repo_url)
    if not repo_path_obj.exists():
        return 0

    cmd = ["-C", str(repo_path_obj), "rev-list", f"{from_sha}..HEAD"]
    if path_filter:
        cmd.extend(["--", path_filter])

    rc, out, _ = run_git(cmd)
    if rc == 0 and out.strip():
        return len([line for line in out.strip().splitlines() if line.strip()])
    return 0


def check_divergence(source_repo_url: str, source_path: str, last_sync_source_sha: str,
                     dest_repo_url: str, dest_path: str, dest_sync_commit_sha: str) -> tuple[bool, bool, bool]:
    source_new = get_new_commits_count(source_repo_url, last_sync_source_sha, source_path) > 0
    dest_new = get_new_commits_count(dest_repo_url, dest_sync_commit_sha, dest_path) > 0
    diverged = source_new and dest_new
    return diverged, source_new, dest_new


def check_pre_apply_patch(source_repo_url: str, source_path: str, last_sync_source_sha: str,
                          dest_repo_url: str, dest_path: str) -> tuple[bool, str]:
    source_path_obj = Path(source_repo_url)
    dest_path_obj = Path(dest_repo_url)

    if str(dest_path_obj).endswith(".git"):
        sibling_working_dir = Path(str(dest_path_obj)[:-4])
        if sibling_working_dir.is_dir():
            dest_path_obj = sibling_working_dir

    if str(source_path_obj).endswith(".git"):
        sibling_working_dir = Path(str(source_path_obj)[:-4])
        if sibling_working_dir.is_dir():
            source_path_obj = sibling_working_dir

    if not source_path_obj.exists() or not dest_path_obj.exists():
        return True, ""

    # Skip git apply check if target destination is bare
    rc, out, _ = run_git(["-C", str(dest_path_obj), "rev-parse", "--is-bare-repository"])
    if rc == 0 and out.strip() == "true":
        return True, ""

    diff_cmd = ["-C", str(source_path_obj), "diff", f"{last_sync_source_sha}..HEAD"]
    if source_path:
        diff_cmd.extend(["--", source_path])

    rc, patch_text, _ = run_git(diff_cmd)
    if rc != 0 or not patch_text.strip():
        return True, ""

    clean_src_path = source_path.strip("/")
    src_parts = [p for p in clean_src_path.split("/") if p]
    strip_level = 1 + len(src_parts)

    clean_dst_path = dest_path.strip("/")

    apply_cmd = ["-C", str(dest_path_obj), "apply", "--check", f"-p{strip_level}"]
    if clean_dst_path:
        apply_cmd.append(f"--directory={clean_dst_path}")

    try:
        res = subprocess.run(
            ["git"] + apply_cmd,
            input=patch_text,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        if res.returncode != 0:
            err_msg = res.stderr.strip() or res.stdout.strip() or f"exit code {res.returncode}"
            return False, err_msg
    except Exception as e:
        return False, str(e)

    return True, ""


def run_preflight_guards(target_name: str, direction: str, target_cfg: dict, manifest: dict, config_path: str, args) -> bool:
    if getattr(args, "skip_guards", False):
        if args.verbose:
            print(f"[VERBOSE] Guard checks explicitly skipped via --skip-guards for {target_name} ({direction})")
        return True

    base_dir = Path(config_path).parent.resolve()

    origin_cfg = target_cfg.get("origin", {})
    hybrid_cfg = target_cfg.get("hybrid", {})

    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")

    origin_url = resolve_repo_url(origin_cfg.get("url", ""), base_dir)
    origin_path = clean_path(origin_cfg.get("path", ""))

    hybrid_url = resolve_repo_url(hybrid_cfg.get("url", default_hybrid_url), base_dir)
    hybrid_path = clean_path(hybrid_cfg.get("path", ""))

    if direction == "push":
        source_url, source_path = origin_url, origin_path
        dest_url, dest_path = hybrid_url, hybrid_path
        source_name, dest_name = "Origin", "Hybrid"
    else:  # pull
        source_url, source_path = hybrid_url, hybrid_path
        dest_url, dest_path = origin_url, origin_path
        source_name, dest_name = "Hybrid", "Origin"

    # --- Guard Check 0: Clean Workspace Check ---
    for r_url, r_label in [(source_url, source_name), (dest_url, dest_name)]:
        uncommitted = check_clean_workspace(r_url)
        if uncommitted:
            print(f"\n{RED}❌ [SAFETY CIRCUIT BREAKER]{RESET} Clean Workspace Guard Failed!", file=sys.stderr)
            print(f"Target '{target_name}' ({direction}): {r_label} repository at '{r_url}' has uncommitted changes:", file=sys.stderr)
            for file_line in uncommitted[:10]:
                print(f"  {file_line}", file=sys.stderr)
            if len(uncommitted) > 10:
                print(f"  ... and {len(uncommitted) - 10} more files.", file=sys.stderr)
            print("Please commit or stash your changes before syncing.", file=sys.stderr)
            return False

    source_last_sync_sha, dest_commit_sha = find_effective_sync_point(source_url, source_path, dest_url, dest_path)

    if not source_last_sync_sha or not dest_commit_sha:
        if args.verbose:
            print(f"[VERBOSE] No previous sync history (GitOrigin-RevId) found between {source_name} and {dest_name} for '{target_name}'. Skipping history/divergence checks.")
        return True

    # --- Guard Check 1: Ancestry & History Check ---
    is_ancestor = check_ancestry_history(source_url, source_last_sync_sha)
    if not is_ancestor:
        print(f"\n{RED}❌ [SAFETY CIRCUIT BREAKER]{RESET} Ancestry & History Guard Failed!", file=sys.stderr)
        print(f"Target '{target_name}' ({direction}): {source_name} commit history was rewritten (force-push or rebase detected).", file=sys.stderr)
        print(f"Recorded last synced commit '{source_last_sync_sha[:8]}' is not in active history lineage of {source_name} ('{source_url}').", file=sys.stderr)
        print("Run with --init-history to re-baseline.", file=sys.stderr)
        return False

    # --- Guard Check 2: Concurrent Fork Check (Divergence Guard) ---
    diverged, source_new, dest_new = check_divergence(
        source_url, source_path, source_last_sync_sha,
        dest_url, dest_path, dest_commit_sha
    )
    if diverged:
        print(f"\n{RED}❌ [SAFETY CIRCUIT BREAKER]{RESET} Concurrent Fork Guard Failed (Divergence Detected)!", file=sys.stderr)
        print(f"Target '{target_name}' ({direction}): Concurrent changes detected in both {source_name} and {dest_name} since last sync point ({source_last_sync_sha[:8]}).", file=sys.stderr)
        print(f"  • {source_name} has new commits in '{source_path or '.'}'", file=sys.stderr)
        print(f"  • {dest_name} has new commits in '{dest_path or '.'}'", file=sys.stderr)
        print("Please pull/merge or resolve manually before syncing.", file=sys.stderr)
        return False

    # --- Guard Check 3: Pre-Apply Patch Check ---
    if source_new:
        patch_ok, patch_err = check_pre_apply_patch(
            source_url, source_path, source_last_sync_sha,
            dest_url, dest_path
        )
        if not patch_ok:
            print(f"\n{RED}❌ [SAFETY CIRCUIT BREAKER]{RESET} Pre-Apply Patch Guard Failed (Structural / Content Conflict)!", file=sys.stderr)
            print(f"Target '{target_name}' ({direction}): Incoming changes from {source_name} cannot be applied cleanly to {dest_name}.", file=sys.stderr)
            print(f"Details: {patch_err}", file=sys.stderr)
            print("Please resolve conflicts manually before syncing.", file=sys.stderr)
            return False

    if args.verbose:
        print(f"[VERBOSE] All pre-flight guard checks PASSED for '{target_name}' ({direction}).")

    return True


def handle_execution(args):
    manifest = load_manifest(args.config)
    targets = manifest.get("targets", {})

    if args.target:
        if args.target not in targets:
            available = ", ".join(targets.keys()) or "none"
            print(f"Error: Target '{args.target}' not found in manifest. Available targets: {available}", file=sys.stderr)
            sys.exit(1)
        target_names = [args.target]
    else:
        target_names = list(targets.keys())

    command = args.command  # 'push', 'pull', or 'sync'

    # Run pre-flight guard checks & collect sync point SHAs
    workflow_last_revs = {}
    base_dir = Path(args.config).parent.resolve()
    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")

    for target_name in target_names:
        t_cfg = targets[target_name]
        if command == "push":
            dirs_to_check = ["push"]
        elif command == "pull":
            dirs_to_check = ["pull"]
        elif command == "sync":
            strategy = getattr(args, "strategy", "push-first")
            dirs_to_check = ["push", "pull"] if strategy == "push-first" else ["pull", "push"]
        else:
            dirs_to_check = []

        for direction in dirs_to_check:
            ok = run_preflight_guards(target_name, direction, t_cfg, manifest, str(args.config), args)
            if not ok:
                sys.exit(1)

            # Resolve effective last synced SHA for Copybara
            origin_cfg = t_cfg.get("origin", {})
            hybrid_cfg = t_cfg.get("hybrid", {})

            origin_url = resolve_repo_url(origin_cfg.get("url", ""), base_dir)
            origin_path = clean_path(origin_cfg.get("path", ""))
            hybrid_url = resolve_repo_url(hybrid_cfg.get("url", default_hybrid_url), base_dir)
            hybrid_path = clean_path(hybrid_cfg.get("path", ""))

            if direction == "push":
                src_url, src_path, dst_url, dst_path = origin_url, origin_path, hybrid_url, hybrid_path
            else:
                src_url, src_path, dst_url, dst_path = hybrid_url, hybrid_path, origin_url, origin_path

            last_sync_sha, _ = find_effective_sync_point(src_url, src_path, dst_url, dst_path)
            dest_has_revid, _ = find_last_sync_info(dst_url, dst_path)
            if last_sync_sha and not dest_has_revid:
                workflow_last_revs[f"{target_name}-{direction}"] = last_sync_sha

    # Determine workflows to run
    workflows = []
    if command == "push":
        workflows = [f"{t}-push" for t in target_names]
    elif command == "pull":
        workflows = [f"{t}-pull" for t in target_names]
    elif command == "sync":
        strategy = getattr(args, "strategy", "push-first")
        if strategy == "push-first":
            workflows = [f"{t}-push" for t in target_names] + [f"{t}-pull" for t in target_names]
        else:  # pull-first
            workflows = [f"{t}-pull" for t in target_names] + [f"{t}-push" for t in target_names]

    sky_content = generate_sky_config(manifest, target_filter=args.target, config_path=str(args.config))

    # Manage working directory for .sky file
    if args.workdir:
        workdir = args.workdir
        workdir.mkdir(parents=True, exist_ok=True)
        sky_path = workdir / "copy.bara.sky"
        sky_path.write_text(sky_content, encoding="utf-8")
        run_workflows(workflows, sky_path, args, workflow_last_revs)
    else:
        with tempfile.TemporaryDirectory(prefix="hybrid_syncer_") as tmp_dir:
            sky_path = Path(tmp_dir) / "copy.bara.sky"
            sky_path.write_text(sky_content, encoding="utf-8")
            run_workflows(workflows, sky_path, args, workflow_last_revs)


def run_workflows(workflows, sky_path: Path, args, workflow_last_revs=None):
    copybara_bin = shutil.which("copybara")
    workflow_last_revs = workflow_last_revs or {}

    if args.verbose:
        print(f"[VERBOSE] Prepared Starlark spec at: {sky_path}")
        print(f"[VERBOSE] Target workflows to run: {', '.join(workflows)}")

    if not copybara_bin:
        print(f"[NOTICE] Copybara binary 'copybara' was not found in PATH.")
        print(f"Temporary Starlark file generated at: {sky_path}")
        print("Would execute the following workflows:")
        for wf in workflows:
            dry_flag = " --dry-run" if args.dry_run else ""
            init_flag = " --init-history" if getattr(args, "init_history", False) else ""
            last_rev_str = f" {workflow_last_revs.get(wf)}" if workflow_last_revs.get(wf) else ""
            print(f"  $ copybara migrate {sky_path} {wf}{last_rev_str}{dry_flag}{init_flag}")
        return

    for wf in workflows:
        cmd = [copybara_bin, "migrate", str(sky_path), wf]
        
        # Append starting revision if a previous sync point exists and init_history is not set
        last_rev = workflow_last_revs.get(wf)
        if last_rev and not getattr(args, "init_history", False):
            cmd.append(last_rev)

        if args.dry_run:
            cmd.append("--dry-run")
        if getattr(args, "init_history", False):
            cmd.append("--init-history")

        if args.verbose:
            print(f"[VERBOSE] Executing: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            stdout=None if args.verbose else subprocess.PIPE,
            stderr=None if args.verbose else subprocess.PIPE,
            text=True
        )

        if result.returncode != 0:
            print(f"Error executing Copybara workflow '{wf}' (exit code {result.returncode})", file=sys.stderr)
            if not args.verbose:
                if result.stdout:
                    print(f"Stdout:\n{result.stdout}", file=sys.stderr)
                if result.stderr:
                    print(f"Stderr:\n{result.stderr}", file=sys.stderr)
            sys.exit(result.returncode)


def format_path_display(path_str: str) -> str:
    if not path_str or path_str == ".":
        return "."
    if not path_str.endswith("/") and "/" not in path_str:
        return path_str + "/"
    return path_str


def handle_status(args):
    manifest = load_manifest(args.config)
    targets = manifest.get("targets", {})
    base_dir = Path(args.config).parent.resolve()
    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")

    if getattr(args, "target", None):
        if args.target not in targets:
            available = ", ".join(targets.keys()) or "none"
            print(f"Error: Target '{args.target}' not found in manifest. Available targets: {available}", file=sys.stderr)
            sys.exit(1)
        targets_to_check = {args.target: targets[args.target]}
    else:
        targets_to_check = targets

    headers = ["Target", "Origin Path", "Hybrid Path", "Origin Status", "Hybrid Status", "Sync Status"]
    rows = []

    for t_name, t_cfg in targets_to_check.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        origin_url = resolve_repo_url(origin_cfg.get("url", ""), base_dir)
        origin_path = clean_path(origin_cfg.get("path", ""))
        hybrid_url = resolve_repo_url(hybrid_cfg.get("url", default_hybrid_url), base_dir)
        hybrid_path = clean_path(hybrid_cfg.get("path", ""))

        origin_path_display = format_path_display(origin_path)
        hybrid_path_display = format_path_display(hybrid_path)

        # Check repository existence
        origin_exists, _ = check_repo_exists(origin_url) if origin_url else (False, "")
        hybrid_exists, _ = check_repo_exists(hybrid_url) if hybrid_url else (False, "")

        if not origin_exists or not hybrid_exists:
            origin_status = "Missing Repo" if not origin_exists else "Clean"
            hybrid_status = "Missing Repo" if not hybrid_exists else "Clean"
            sync_status = "Repository Not Found"
            rows.append((t_name, origin_path_display, hybrid_path_display, origin_status, hybrid_status, sync_status))
            continue

        # Check uncommitted local changes
        origin_uncommitted = check_clean_workspace(origin_url)
        hybrid_uncommitted = check_clean_workspace(hybrid_url)

        source_last_sync_sha, dest_commit_sha = find_effective_sync_point(origin_url, origin_path, hybrid_url, hybrid_path)

        if not source_last_sync_sha or not dest_commit_sha:
            origin_status = f"Dirty ({len(origin_uncommitted)})" if origin_uncommitted else "Untracked"
            hybrid_status = f"Dirty ({len(hybrid_uncommitted)})" if hybrid_uncommitted else "Untracked"
            sync_status = "Untracked / No Sync History"
        else:
            ancestry_ok = check_ancestry_history(origin_url, source_last_sync_sha) and check_ancestry_history(hybrid_url, dest_commit_sha)

            origin_ahead = get_new_commits_count(origin_url, source_last_sync_sha, origin_path)
            hybrid_ahead = get_new_commits_count(hybrid_url, dest_commit_sha, hybrid_path)

            diverged = origin_ahead > 0 and hybrid_ahead > 0

            # Origin Status string
            orig_parts = []
            if origin_ahead > 0:
                orig_parts.append(f"Ahead ({origin_ahead})")
            if origin_uncommitted:
                orig_parts.append(f"Dirty ({len(origin_uncommitted)})" if not origin_ahead else "[Dirty]")
            origin_status = " ".join(orig_parts) if orig_parts else "Clean"

            # Hybrid Status string
            hyb_parts = []
            if hybrid_ahead > 0:
                hyb_parts.append(f"Ahead ({hybrid_ahead})")
            if hybrid_uncommitted:
                hyb_parts.append(f"Dirty ({len(hybrid_uncommitted)})" if not hybrid_ahead else "[Dirty]")
            hybrid_status = " ".join(hyb_parts) if hyb_parts else "Clean"

            # Sync Status
            if not ancestry_ok:
                sync_status = "⚠️ History Rewritten"
            elif diverged:
                sync_status = "⚠️ DIVERGED (Conflict)"
            elif origin_ahead > 0:
                sync_status = "Ready to Push"
            elif hybrid_ahead > 0:
                sync_status = "Ready to Pull"
            else:
                sync_status = "In Sync"

        rows.append((t_name, origin_path_display, hybrid_path_display, origin_status, hybrid_status, sync_status))

    # Calculate column widths
    min_widths = [15, 15, 15, 15, 15, 20]
    col_widths = [max(min_w, len(h)) for min_w, h in zip(min_widths, headers)]

    for row in rows:
        for i, val in enumerate(row):
            col_widths[i] = max(col_widths[i], len(val))

    # Format table
    header_line = "  ".join(f"{headers[i]:<{col_widths[i]}}" for i in range(len(headers)))
    sep_line = "-" * len(header_line)

    print(f"\n{header_line}")
    print(sep_line)
    for row in rows:
        row_line = "  ".join(f"{row[i]:<{col_widths[i]}}" for i in range(len(headers)))
        print(row_line)
    print()

    if getattr(args, "check_unmapped", False):
        analyze_unmapped_origin_paths(manifest, base_dir, target_filter=getattr(args, "target", ""))


def is_file_mapped(file_path: str, mapped_paths: set[str]) -> bool:
    if "" in mapped_paths or "." in mapped_paths:
        return True
    clean_f = clean_path(file_path)
    for mp in mapped_paths:
        clean_m = clean_path(mp)
        if not clean_m:
            return True
        if clean_f == clean_m or clean_f.startswith(clean_m + "/"):
            return True
    return False


def analyze_unmapped_origin_paths(manifest: dict, base_dir: Path, target_filter: str = ""):
    targets = manifest.get("targets", {})
    if target_filter:
        if target_filter in targets:
            targets_to_check = {target_filter: targets[target_filter]}
        else:
            targets_to_check = targets
    else:
        targets_to_check = targets

    # Group mapped origin paths by origin repository URL
    origin_mapped = {}  # origin_url -> set(mapped_paths)
    origin_targets = {}  # origin_url -> list(target_names)

    for t_name, t_cfg in targets_to_check.items():
        o_cfg = t_cfg.get("origin", {})
        o_url = resolve_repo_url(o_cfg.get("url", ""), base_dir)
        o_path = clean_path(o_cfg.get("path", ""))

        if not o_url:
            continue
        if o_url not in origin_mapped:
            origin_mapped[o_url] = set()
            origin_targets[o_url] = []

        origin_mapped[o_url].add(o_path)
        origin_targets[o_url].append(t_name)

    print("\n🔍 Unmapped & Orphan Path Analysis (Origin Repositories):")
    print("-" * 80)

    total_unmapped_tracked = 0
    total_unmapped_local = 0

    for o_url, mapped_paths in origin_mapped.items():
        if not o_url or is_remote_url(o_url):
            continue
        repo_path = Path(o_url)
        if not repo_path.exists():
            continue

        # Check if bare
        actual_repo_path = repo_path
        rc, out, _ = run_git(["-C", str(repo_path), "rev-parse", "--is-bare-repository"])
        if rc == 0 and out.strip() == "true" and str(repo_path).endswith(".git"):
            sibling = Path(str(repo_path)[:-4])
            if sibling.is_dir():
                actual_repo_path = sibling

        # 1. Check tracked files in repository
        rc, out, _ = run_git(["-C", str(actual_repo_path), "ls-files"])
        tracked_files = [line.strip() for line in out.strip().splitlines() if line.strip()] if rc == 0 and out.strip() else []

        unmapped_tracked = [f for f in tracked_files if not is_file_mapped(f, mapped_paths)]

        # 2. Check uncommitted local changes
        uncommitted_lines = check_clean_workspace(str(actual_repo_path))
        unmapped_local = []
        for line in uncommitted_lines:
            parts = line.strip().split(maxsplit=1)
            if len(parts) == 2:
                file_p = parts[1].strip()
                if " -> " in file_p:
                    file_p = file_p.split(" -> ")[-1].strip()
                if not is_file_mapped(file_p, mapped_paths):
                    unmapped_local.append((parts[0], file_p))

        if unmapped_tracked or unmapped_local:
            total_unmapped_tracked += len(unmapped_tracked)
            total_unmapped_local += len(unmapped_local)

            display_paths = ", ".join([f"{p}/" if p else "." for p in sorted(mapped_paths)]) or "."
            t_names = ", ".join(origin_targets[o_url])

            print(f"Repository: {o_url} (Targets: {t_names})")
            print(f"  Mapped Target Paths : {display_paths}")

            if unmapped_tracked:
                print(f"  Tracked Orphan Files ({len(unmapped_tracked)}):")
                for uf in unmapped_tracked[:10]:
                    print(f"    • {uf}")
                if len(unmapped_tracked) > 10:
                    print(f"    ... and {len(unmapped_tracked) - 10} more tracked file(s).")

            if unmapped_local:
                print(f"  Uncommitted Orphan Files ({len(unmapped_local)}):")
                for st, uf in unmapped_local[:10]:
                    print(f"    • [{st}] {uf}")
                if len(unmapped_local) > 10:
                    print(f"    ... and {len(unmapped_local) - 10} more uncommitted file(s).")
            print()

    if total_unmapped_tracked == 0 and total_unmapped_local == 0:
        print(f"✔ No unmapped files or orphan paths detected across {len(origin_mapped)} origin repository(ies). All files match defined target paths.\n")
    else:
        print(f"⚠️ Notice: Detected {total_unmapped_tracked} tracked and {total_unmapped_local} uncommitted orphan file(s) outside defined target paths.")
        print("          These files are outside any target's origin.path and will NOT be synced to hybrid repository.\n")


def check_manifest_health(manifest: dict, config_path: Path = Path("sync-manifest.yaml")) -> tuple[int, int]:
    targets = manifest.get("targets", {})
    base_dir = config_path.parent.resolve()
    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")

    errors = []
    warnings = []

    print(f"\n🩺 Running Hybrid Syncer Health Check on '{config_path}'...\n")

    # 1. Missing Local Repositories Check
    checked_repos = set()
    for t_name, t_cfg in targets.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        origin_url = resolve_repo_url(origin_cfg.get("url", ""), base_dir)
        hybrid_url = resolve_repo_url(hybrid_cfg.get("url", default_hybrid_url), base_dir)

        if origin_url and origin_url not in checked_repos:
            checked_repos.add(origin_url)
            exists, err_msg = check_repo_exists(origin_url)
            if not exists:
                errors.append(f"Target '{t_name}': Origin repository URL '{origin_url}' {err_msg}")

        if hybrid_url and hybrid_url not in checked_repos:
            checked_repos.add(hybrid_url)
            exists, err_msg = check_repo_exists(hybrid_url)
            if not exists:
                errors.append(f"Target '{t_name}': Hybrid repository URL '{hybrid_url}' {err_msg}")

    # 2. Hybrid Path Clashes & Prefix Overlaps
    hybrid_paths = {}
    for t_name, t_cfg in targets.items():
        h_path = clean_path(t_cfg.get("hybrid", {}).get("path", ""))
        for existing_target, existing_path in hybrid_paths.items():
            if h_path == existing_path:
                errors.append(f"Target '{t_name}' clashes with '{existing_target}' at hybrid path '{h_path or '.'}'")
            elif h_path and existing_path:
                if h_path.startswith(existing_path + "/") or existing_path.startswith(h_path + "/"):
                    warnings.append(f"Target '{t_name}' ({h_path}) overlaps with '{existing_target}' ({existing_path})")
            elif not h_path or not existing_path:
                warnings.append(f"Target '{t_name}' ({h_path or '.'}) overlaps with root path of '{existing_target}' ({existing_path or '.'})")
        hybrid_paths[t_name] = h_path

    # 3. Origin Path Clashes & Prefix Overlaps (Within the Same Origin Repo)
    origin_paths = {}  # repo_url -> dict(target_name -> o_path)
    for t_name, t_cfg in targets.items():
        o_url = resolve_repo_url(t_cfg.get("origin", {}).get("url", ""), base_dir)
        o_path = clean_path(t_cfg.get("origin", {}).get("path", ""))
        if not o_url:
            continue
        if o_url not in origin_paths:
            origin_paths[o_url] = {}
        for existing_target, existing_path in origin_paths[o_url].items():
            if o_path == existing_path:
                errors.append(f"Target '{t_name}' clashes with '{existing_target}' at origin path '{o_path or '.'}' in '{o_url}'")
            elif o_path and existing_path:
                if o_path.startswith(existing_path + "/") or existing_path.startswith(o_path + "/"):
                    warnings.append(f"Target '{t_name}' origin path ({o_path}) overlaps with '{existing_target}' ({existing_path}) in '{o_url}'")
        origin_paths[o_url][t_name] = o_path

    # Output findings
    if errors:
        for err in errors:
            print(f"❌ Error: {err}")
    if warnings:
        for warn in warnings:
            print(f"⚠️ Warning: {warn}")

    if not errors and not warnings:
        print(f"✔ All {len(targets)} manifest target(s) passed health checks cleanly with 0 errors and 0 warnings.")
    else:
        print(f"\nManifest Health Summary: {len(errors)} error(s), {len(warnings)} warning(s) detected across {len(targets)} target(s).")

    return len(errors), len(warnings)


def handle_doctor(args):
    manifest = load_manifest(args.config)
    num_errors, _ = check_manifest_health(manifest, config_path=args.config)
    if num_errors > 0:
        sys.exit(1)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hybrid-syncer",
        description="A lightweight wrapper to generate Starlark configs and execute Copybara syncs.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Global options
    parser.add_argument(
        "-c", "--config",
        type=Path,
        default=Path("sync-manifest.yaml"),
        help="Path to sync manifest YAML"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output and raw Copybara execution logs"
    )
    parser.add_argument(
        "-w", "--workdir",
        type=Path,
        default=None,
        help="Custom directory for temporary .sky files and working files"
    )

    subparsers = parser.add_subparsers(dest="command", required=True, title="subcommands")

    # Reusable flags for execution subcommands (push, pull, sync)
    exec_parent = argparse.ArgumentParser(add_help=False)
    exec_parent.add_argument(
        "-t", "--target",
        type=str,
        help="Run sync only for a specific mapping name (e.g. repo-1-a)"
    )
    exec_parent.add_argument(
        "-n", "--dry-run",
        action="store_true",
        help="Pass --dry-run to Copybara without modifying remotes"
    )
    exec_parent.add_argument(
        "--init-history",
        action="store_true",
        help="Pass --init-history to Copybara for first-time migration setup"
    )
    exec_parent.add_argument(
        "--skip-guards",
        action="store_true",
        help="Skip pre-flight safety circuit breaker guard checks"
    )

    # Subcommand: push
    push_parser = subparsers.add_parser(
        "push",
        parents=[exec_parent],
        help="Sync changes from origin repositories -> hybrid repo"
    )
    push_parser.set_defaults(func=handle_execution)

    # Subcommand: pull
    pull_parser = subparsers.add_parser(
        "pull",
        parents=[exec_parent],
        help="Sync changes from hybrid repo -> origin repositories"
    )
    pull_parser.set_defaults(func=handle_execution)

    # Subcommand: sync
    sync_parser = subparsers.add_parser(
        "sync",
        parents=[exec_parent],
        help="Perform bi-directional sync (push followed by pull)"
    )
    sync_parser.add_argument(
        "--strategy",
        choices=["push-first", "pull-first"],
        default="push-first",
        help="Order of sync operations"
    )
    sync_parser.set_defaults(func=handle_execution)

    # Subcommand: status
    status_parser = subparsers.add_parser(
        "status",
        help="Show synchronization state and workspace status for all targets"
    )
    status_parser.add_argument(
        "-t", "--target",
        type=str,
        help="Filter status check to a specific target"
    )
    status_parser.add_argument(
        "--check-unmapped",
        action="store_true",
        help="Analyze origin repositories for unmapped/orphan files outside defined target paths"
    )
    status_parser.set_defaults(func=handle_status)

    # Subcommand: doctor / detector
    doctor_parser = subparsers.add_parser(
        "doctor",
        aliases=["detector"],
        help="Run manifest health check to detect path clashes, overlaps, and missing repositories"
    )
    doctor_parser.set_defaults(func=handle_doctor)

    # Subcommand: generate
    gen_parser = subparsers.add_parser(
        "generate",
        help="Generate copybara.sky configuration file without executing sync"
    )
    gen_parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Output path for .sky file (prints to stdout if omitted)"
    )
    gen_parser.add_argument(
        "-t", "--target",
        type=str,
        help="Filter generation to specific target"
    )
    gen_parser.set_defaults(func=handle_generate)

    # Subcommand: init
    init_parser = subparsers.add_parser(
        "init",
        help="Initialize a starter sync-manifest.yaml"
    )
    init_parser.add_argument(
        "-f", "--force",
        action="store_true",
        help="Force overwrite of existing sync-manifest.yaml"
    )
    init_parser.set_defaults(func=handle_init)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
