#!/usr/bin/env python3
import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
import yaml

STARTER_MANIFEST = """# hybrid-syncer configuration manifest
hybrid_repo: "./sample-repos/hybrid"
default_branch: "master"

authoring:
  default_email: "syncer@example.com"
  default_name: "Hybrid Syncer"

targets:
  repo-1-a:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "a"
    hybrid:
      path: "repo-1/a"

  repo-1-b:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "b"
    hybrid:
      path: "repo-1/b"

  repo-2-a:
    origin:
      url: "./sample-repos/repo-2.git"
      path: "a"
    hybrid:
      path: "repo-2/a"
"""


def clean_path(p) -> str:
    if not p or p == ".":
        return ""
    return str(p).strip("/")


def load_manifest(config_path: Path) -> dict:
    if not config_path.exists():
        print(f"Error: Configuration file '{config_path}' not found.", file=sys.stderr)
        print("Run 'hybrid-syncer init' to create a starter sync-manifest.yaml.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception as e:
        print(f"Error reading configuration file '{config_path}': {e}", file=sys.stderr)
        sys.exit(1)

    if "targets" not in data or not isinstance(data.get("targets"), dict):
        print(f"Error: Invalid manifest format in '{config_path}'. 'targets' section missing or invalid.", file=sys.stderr)
        sys.exit(1)

    return data


def resolve_repo_url(url: str, base_dir: Path) -> str:
    if not url:
        return ""
    if url.startswith(("http://", "https://", "git@", "ssh://", "file://")):
        return url
    p = Path(url)
    if not p.is_absolute():
        p = (base_dir / p).resolve()
    return str(p)


def generate_sky_config(manifest: dict, target_filter: str = None, config_path: str = "sync-manifest.yaml") -> str:
    targets = manifest.get("targets", {})
    base_dir = Path(config_path).parent.resolve()

    if target_filter:
        if target_filter not in targets:
            available = ", ".join(targets.keys()) or "none"
            print(f"Error: Target '{target_filter}' not found in manifest. Available targets: {available}", file=sys.stderr)
            sys.exit(1)
        targets_to_gen = {target_filter: targets[target_filter]}
    else:
        targets_to_gen = targets

    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")
    default_branch = manifest.get("default_branch", "main")
    authoring_cfg = manifest.get("authoring", {})
    author_email = authoring_cfg.get("default_email", "syncer@example.com")
    author_name = authoring_cfg.get("default_name", "Hybrid Syncer")
    author_str = f"{author_name} <{author_email}>"

    lines = [
        f"# Generated by hybrid-syncer from {config_path}",
        "# Do not edit manually.",
        ""
    ]

    for t_name, t_cfg in targets_to_gen.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        raw_origin_url = origin_cfg.get("url")
        if not raw_origin_url:
            print(f"Error: Target '{t_name}' is missing origin.url", file=sys.stderr)
            sys.exit(1)

        origin_url = resolve_repo_url(raw_origin_url, base_dir)
        origin_branch = origin_cfg.get("branch", default_branch)
        origin_path = clean_path(origin_cfg.get("path", ""))

        raw_hybrid_url = hybrid_cfg.get("url", default_hybrid_url)
        hybrid_url = resolve_repo_url(raw_hybrid_url, base_dir)
        hybrid_branch = hybrid_cfg.get("branch", default_branch)
        hybrid_path = clean_path(hybrid_cfg.get("path", ""))

        mode = t_cfg.get("mode", "ITERATIVE")

        # Origin files & destination files patterns
        origin_files_push = f'glob(["{origin_path}/**"])' if origin_path else 'glob(["**"])'
        dest_files_push = f'glob(["{hybrid_path}/**"])' if hybrid_path else 'glob(["**"])'

        # Transformations for push
        push_trans = ""
        if origin_path != hybrid_path:
            push_trans = f'\n    transformations = [\n        core.move("{origin_path}", "{hybrid_path}"),\n    ],'

        # Workflow: push
        lines.append(f"# Target: {t_name} (push)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-push",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        ref = "{origin_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        fetch = "{hybrid_branch}",')
        lines.append(f'        push = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {origin_files_push},")
        lines.append(f"    destination_files = {dest_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{push_trans}')
        lines.append(")")
        lines.append("")

        # Transformations for pull
        pull_trans = ""
        if hybrid_path != origin_path:
            pull_trans = f'\n    transformations = [\n        core.move("{hybrid_path}", "{origin_path}"),\n    ],'

        # Workflow: pull
        lines.append(f"# Target: {t_name} (pull)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-pull",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        ref = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        fetch = "{origin_branch}",')
        lines.append(f'        push = "{origin_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {dest_files_push},")
        lines.append(f"    destination_files = {origin_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{pull_trans}')
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def handle_init(args):
    config_path = args.config
    if config_path.exists() and not args.force:
        print(f"Error: File '{config_path}' already exists. Use -f / --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    try:
        if config_path.parent:
            config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(STARTER_MANIFEST, encoding="utf-8")
        print(f"Initialized starter sync manifest at: {config_path}")
    except Exception as e:
        print(f"Error writing manifest to '{config_path}': {e}", file=sys.stderr)
        sys.exit(1)


def handle_generate(args):
    manifest = load_manifest(args.config)
    sky_content = generate_sky_config(manifest, target_filter=args.target, config_path=str(args.config))

    if args.output:
        try:
            if args.output.parent:
                args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(sky_content, encoding="utf-8")
            print(f"Generated Starlark configuration written to: {args.output}")
        except Exception as e:
            print(f"Error writing output to '{args.output}': {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(sky_content)


def handle_execution(args):
    manifest = load_manifest(args.config)
    targets = manifest.get("targets", {})

    if args.target:
        if args.target not in targets:
            available = ", ".join(targets.keys()) or "none"
            print(f"Error: Target '{args.target}' not found in manifest. Available targets: {available}", file=sys.stderr)
            sys.exit(1)
        target_names = [args.target]
    else:
        target_names = list(targets.keys())

    command = args.command  # 'push', 'pull', or 'sync'

    # Determine workflows to run
    workflows = []
    if command == "push":
        workflows = [f"{t}-push" for t in target_names]
    elif command == "pull":
        workflows = [f"{t}-pull" for t in target_names]
    elif command == "sync":
        strategy = getattr(args, "strategy", "push-first")
        if strategy == "push-first":
            workflows = [f"{t}-push" for t in target_names] + [f"{t}-pull" for t in target_names]
        else:  # pull-first
            workflows = [f"{t}-pull" for t in target_names] + [f"{t}-push" for t in target_names]

    sky_content = generate_sky_config(manifest, target_filter=args.target, config_path=str(args.config))

    # Manage working directory for .sky file
    if args.workdir:
        workdir = args.workdir
        workdir.mkdir(parents=True, exist_ok=True)
        sky_path = workdir / "copy.bara.sky"
        sky_path.write_text(sky_content, encoding="utf-8")
        run_workflows(workflows, sky_path, args)
    else:
        with tempfile.TemporaryDirectory(prefix="hybrid_syncer_") as tmp_dir:
            sky_path = Path(tmp_dir) / "copy.bara.sky"
            sky_path.write_text(sky_content, encoding="utf-8")
            run_workflows(workflows, sky_path, args)


def run_workflows(workflows, sky_path: Path, args):
    copybara_bin = shutil.which("copybara")

    if args.verbose:
        print(f"[VERBOSE] Prepared Starlark spec at: {sky_path}")
        print(f"[VERBOSE] Target workflows to run: {', '.join(workflows)}")

    if not copybara_bin:
        print(f"[NOTICE] Copybara binary 'copybara' was not found in PATH.")
        print(f"Temporary Starlark file generated at: {sky_path}")
        print("Would execute the following workflows:")
        for wf in workflows:
            dry_flag = " --dry-run" if args.dry_run else ""
            init_flag = " --init-history" if getattr(args, "init_history", False) else ""
            print(f"  $ copybara migrate {sky_path} {wf}{dry_flag}{init_flag}")
        return

    for wf in workflows:
        cmd = [copybara_bin, "migrate", str(sky_path), wf]
        if args.dry_run:
            cmd.append("--dry-run")
        if getattr(args, "init_history", False):
            cmd.append("--init-history")

        if args.verbose:
            print(f"[VERBOSE] Executing: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            stdout=None if args.verbose else subprocess.PIPE,
            stderr=None if args.verbose else subprocess.PIPE,
            text=True
        )

        if result.returncode != 0:
            print(f"Error executing Copybara workflow '{wf}' (exit code {result.returncode})", file=sys.stderr)
            if not args.verbose:
                if result.stdout:
                    print(f"Stdout:\n{result.stdout}", file=sys.stderr)
                if result.stderr:
                    print(f"Stderr:\n{result.stderr}", file=sys.stderr)
            sys.exit(result.returncode)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hybrid-syncer",
        description="A lightweight wrapper to generate Starlark configs and execute Copybara syncs.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Global options
    parser.add_argument(
        "-c", "--config",
        type=Path,
        default=Path("sync-manifest.yaml"),
        help="Path to sync manifest YAML"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output and raw Copybara execution logs"
    )
    parser.add_argument(
        "-w", "--workdir",
        type=Path,
        default=None,
        help="Custom directory for temporary .sky files and working files"
    )

    subparsers = parser.add_subparsers(dest="command", required=True, title="subcommands")

    # Reusable flags for execution subcommands (push, pull, sync)
    exec_parent = argparse.ArgumentParser(add_help=False)
    exec_parent.add_argument(
        "-t", "--target",
        type=str,
        help="Run sync only for a specific mapping name (e.g. repo-1-a)"
    )
    exec_parent.add_argument(
        "-n", "--dry-run",
        action="store_true",
        help="Pass --dry-run to Copybara without modifying remotes"
    )
    exec_parent.add_argument(
        "--init-history",
        action="store_true",
        help="Pass --init-history to Copybara for first-time migration setup"
    )

    # Subcommand: push
    push_parser = subparsers.add_parser(
        "push",
        parents=[exec_parent],
        help="Sync changes from origin repositories -> hybrid repo"
    )
    push_parser.set_defaults(func=handle_execution)

    # Subcommand: pull
    pull_parser = subparsers.add_parser(
        "pull",
        parents=[exec_parent],
        help="Sync changes from hybrid repo -> origin repositories"
    )
    pull_parser.set_defaults(func=handle_execution)

    # Subcommand: sync
    sync_parser = subparsers.add_parser(
        "sync",
        parents=[exec_parent],
        help="Perform bi-directional sync (push followed by pull)"
    )
    sync_parser.add_argument(
        "--strategy",
        choices=["push-first", "pull-first"],
        default="push-first",
        help="Order of sync operations"
    )
    sync_parser.set_defaults(func=handle_execution)

    # Subcommand: generate
    gen_parser = subparsers.add_parser(
        "generate",
        help="Generate copybara.sky configuration file without executing sync"
    )
    gen_parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Output path for .sky file (prints to stdout if omitted)"
    )
    gen_parser.add_argument(
        "-t", "--target",
        type=str,
        help="Filter generation to specific target"
    )
    gen_parser.set_defaults(func=handle_generate)

    # Subcommand: init
    init_parser = subparsers.add_parser(
        "init",
        help="Initialize a starter sync-manifest.yaml"
    )
    init_parser.add_argument(
        "-f", "--force",
        action="store_true",
        help="Force overwrite of existing sync-manifest.yaml"
    )
    init_parser.set_defaults(func=handle_init)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
