"""
Manifest loading, validation, and Copybara Starlark sky generation.
"""

import sys
from pathlib import Path
import yaml

from hybrid_syncer.errors import ManifestError
from hybrid_syncer.git_utils import check_repo_exists, resolve_repo_url

STARTER_MANIFEST = """# hybrid-syncer configuration manifest
hybrid_repo: "./sample-repos/hybrid"
default_branch: "master"

authoring:
  default_email: "syncer@example.com"
  default_name: "Hybrid Syncer"

targets:
  repo-1-a:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "a"
    hybrid:
      path: "repo-1/a"

  repo-1-b:
    origin:
      url: "./sample-repos/repo-1.git"
      path: "b"
    hybrid:
      path: "repo-1/b"

  repo-2-a:
    origin:
      url: "./sample-repos/repo-2.git"
      path: "a"
    hybrid:
      path: "repo-2/a"
"""


def clean_path(p) -> str:
    if not p or p == ".":
        return ""
    return str(p).replace("\\", "/").strip("/")


def load_manifest(config_path: Path) -> dict:
    if not config_path.exists():
        raise ManifestError(f"Configuration file '{config_path}' not found.\nRun 'hybrid-syncer init' to create a starter sync-manifest.yaml.")

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except (yaml.YAMLError, OSError) as e:
        raise ManifestError(f"Error reading configuration file '{config_path}': {e}")

    if "targets" not in data or not isinstance(data.get("targets"), dict):
        raise ManifestError(f"Invalid manifest format in '{config_path}'. 'targets' section missing or invalid.")

    return data


def format_exclude_pattern(pattern: str, base_path: str) -> list[str]:
    pattern = pattern.strip()
    if not base_path:
        return [pattern]
    if pattern.startswith(base_path + "/"):
        return [pattern]
    if pattern.startswith("**/"):
        suffix = pattern[3:]
        return [f"{base_path}/{suffix}", f"{base_path}/**/{suffix}"]
    return [f"{base_path}/{pattern}"]


def build_glob_expr(base_path: str, exclude_patterns: list[str] | None = None) -> str:
    include_pattern = f"{base_path}/**" if base_path else "**"

    if not exclude_patterns:
        return f'glob(["{include_pattern}"])'

    formatted_excludes = []
    for p in exclude_patterns:
        if isinstance(p, str) and p.strip():
            formatted_excludes.extend(format_exclude_pattern(p, base_path))

    if not formatted_excludes:
        return f'glob(["{include_pattern}"])'

    excludes_str = ", ".join(f'"{p}"' for p in formatted_excludes)
    return f'glob(["{include_pattern}"], exclude = [{excludes_str}])'


def generate_sky_config(manifest: dict, target_filter: str = "", config_path: str = "sync-manifest.yaml") -> str:
    targets = manifest.get("targets", {})
    base_dir = Path(config_path).parent.resolve()

    if target_filter:
        if target_filter not in targets:
            available = ", ".join(targets.keys()) or "none"
            raise ManifestError(f"Target '{target_filter}' not found in manifest. Available targets: {available}")
        targets_to_gen = {target_filter: targets[target_filter]}
    else:
        targets_to_gen = targets

    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")
    default_branch = manifest.get("default_branch", "main")
    authoring_cfg = manifest.get("authoring", {})
    author_email = authoring_cfg.get("default_email", "syncer@example.com")
    author_name = authoring_cfg.get("default_name", "Hybrid Syncer")
    author_str = f"{author_name} <{author_email}>"

    lines = [
        f"# Generated by hybrid-syncer from {config_path}",
        "# Do not edit manually.",
        ""
    ]

    for t_name, t_cfg in targets_to_gen.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        raw_origin_url = origin_cfg.get("url")
        if not raw_origin_url:
            raise ManifestError(f"Target '{t_name}' is missing origin.url")

        origin_url = resolve_repo_url(raw_origin_url, base_dir)
        origin_branch = origin_cfg.get("branch", default_branch)
        origin_path = clean_path(origin_cfg.get("path", ""))

        raw_hybrid_url = hybrid_cfg.get("url", default_hybrid_url)
        hybrid_url = resolve_repo_url(raw_hybrid_url, base_dir)
        hybrid_branch = hybrid_cfg.get("branch", default_branch)
        hybrid_path = clean_path(hybrid_cfg.get("path", ""))

        mode = t_cfg.get("mode", "ITERATIVE")

        # Collect exclusion patterns
        target_exclude = t_cfg.get("exclude", [])
        if isinstance(target_exclude, str):
            target_exclude = [target_exclude]
        elif not isinstance(target_exclude, list):
            target_exclude = []

        origin_exclude_raw = origin_cfg.get("exclude", [])
        if isinstance(origin_exclude_raw, str):
            origin_exclude_raw = [origin_exclude_raw]
        elif not isinstance(origin_exclude_raw, list):
            origin_exclude_raw = []

        hybrid_exclude_raw = hybrid_cfg.get("exclude", [])
        if isinstance(hybrid_exclude_raw, str):
            hybrid_exclude_raw = [hybrid_exclude_raw]
        elif not isinstance(hybrid_exclude_raw, list):
            hybrid_exclude_raw = []

        origin_exclude = origin_exclude_raw + target_exclude
        hybrid_exclude = hybrid_exclude_raw + target_exclude

        # Origin files & destination files patterns
        origin_files_push = build_glob_expr(origin_path, origin_exclude)
        dest_files_push = build_glob_expr(hybrid_path, hybrid_exclude)

        # Transformations for push
        push_trans = ""
        if origin_path != hybrid_path:
            push_trans = f'\n    transformations = [\n        core.move("{origin_path}", "{hybrid_path}"),\n    ],'

        # Workflow: push
        lines.append(f"# Target: {t_name} (push)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-push",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        ref = "{origin_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        fetch = "{hybrid_branch}",')
        lines.append(f'        push = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {origin_files_push},")
        lines.append(f"    destination_files = {dest_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{push_trans}')
        lines.append(")")
        lines.append("")

        # Transformations for pull
        pull_trans = ""
        if hybrid_path != origin_path:
            pull_trans = f'\n    transformations = [\n        core.move("{hybrid_path}", "{origin_path}"),\n    ],'

        # Workflow: pull
        lines.append(f"# Target: {t_name} (pull)")
        lines.append("core.workflow(")
        lines.append(f'    name = "{t_name}-pull",')
        lines.append("    origin = git.origin(")
        lines.append(f'        url = "{hybrid_url}",')
        lines.append(f'        ref = "{hybrid_branch}",')
        lines.append("    ),")
        lines.append("    destination = git.destination(")
        lines.append(f'        url = "{origin_url}",')
        lines.append(f'        fetch = "{origin_branch}",')
        lines.append(f'        push = "{origin_branch}",')
        lines.append("    ),")
        lines.append(f"    origin_files = {dest_files_push},")
        lines.append(f"    destination_files = {origin_files_push},")
        lines.append(f'    authoring = authoring.pass_thru(default = "{author_str}"),')
        lines.append(f'    mode = "{mode}",{pull_trans}')
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def check_manifest_health(manifest: dict, config_path: Path = Path("sync-manifest.yaml")) -> tuple[int, int]:
    targets = manifest.get("targets", {})
    base_dir = config_path.parent.resolve()
    default_hybrid_url = manifest.get("hybrid_repo", "./hybrid")

    errors = []
    warnings = []

    print(f"\n🩺 Running Hybrid Syncer Health Check on '{config_path}'...\n", file=sys.stderr)

    # 1. Missing Local Repositories Check
    checked_repos = set()
    for t_name, t_cfg in targets.items():
        origin_cfg = t_cfg.get("origin", {})
        hybrid_cfg = t_cfg.get("hybrid", {})

        origin_url = resolve_repo_url(origin_cfg.get("url", ""), base_dir)
        hybrid_url = resolve_repo_url(hybrid_cfg.get("url", default_hybrid_url), base_dir)

        if origin_url and origin_url not in checked_repos:
            checked_repos.add(origin_url)
            exists, err_msg = check_repo_exists(origin_url)
            if not exists:
                errors.append(f"Target '{t_name}': Origin repository URL '{origin_url}' {err_msg}")

        if hybrid_url and hybrid_url not in checked_repos:
            checked_repos.add(hybrid_url)
            exists, err_msg = check_repo_exists(hybrid_url)
            if not exists:
                errors.append(f"Target '{t_name}': Hybrid repository URL '{hybrid_url}' {err_msg}")

    # 2. Hybrid Path Clashes & Prefix Overlaps
    hybrid_paths = {}
    for t_name, t_cfg in targets.items():
        h_path = clean_path(t_cfg.get("hybrid", {}).get("path", ""))
        for existing_target, existing_path in hybrid_paths.items():
            if h_path == existing_path:
                errors.append(f"Target '{t_name}' clashes with '{existing_target}' at hybrid path '{h_path or '.'}'")
            elif h_path and existing_path:
                if h_path.startswith(existing_path + "/") or existing_path.startswith(h_path + "/"):
                    warnings.append(f"Target '{t_name}' ({h_path}) overlaps with '{existing_target}' ({existing_path})")
            elif not h_path or not existing_path:
                warnings.append(f"Target '{t_name}' ({h_path or '.'}) overlaps with root path of '{existing_target}' ({existing_path or '.'})")
        hybrid_paths[t_name] = h_path

    # 3. Origin Path Clashes & Prefix Overlaps (Within the Same Origin Repo)
    origin_paths = {}  # repo_url -> dict(target_name -> o_path)
    for t_name, t_cfg in targets.items():
        o_url = resolve_repo_url(t_cfg.get("origin", {}).get("url", ""), base_dir)
        o_path = clean_path(t_cfg.get("origin", {}).get("path", ""))
        if not o_url:
            continue
        if o_url not in origin_paths:
            origin_paths[o_url] = {}
        for existing_target, existing_path in origin_paths[o_url].items():
            if o_path == existing_path:
                errors.append(f"Target '{t_name}' clashes with '{existing_target}' at origin path '{o_path or '.'}' in '{o_url}'")
            elif o_path and existing_path:
                if o_path.startswith(existing_path + "/") or existing_path.startswith(o_path + "/"):
                    warnings.append(f"Target '{t_name}' origin path ({o_path}) overlaps with '{existing_target}' ({existing_path}) in '{o_url}'")
        origin_paths[o_url][t_name] = o_path

    # Output findings to stderr
    if errors:
        for err in errors:
            print(f"❌ Error: {err}", file=sys.stderr)
    if warnings:
        for warn in warnings:
            print(f"⚠️ Warning: {warn}", file=sys.stderr)

    if not errors and not warnings:
        print(f"✔ All {len(targets)} manifest target(s) passed health checks cleanly with 0 errors and 0 warnings.", file=sys.stderr)
    else:
        print(f"\nManifest Health Summary: {len(errors)} error(s), {len(warnings)} warning(s) detected across {len(targets)} target(s).", file=sys.stderr)

    return len(errors), len(warnings)
